spring:
  application:
    name: rabbitmq
  rabbitmq:
    host: rabbit-mq
    port: 5672
    username: guest
    password: guest
    string-queue:
      name: my-queue
    json-queue:
      name: json-queue
    exchange:
      name: my-exchange
    routing-key:
      string:
        name: my-routing-key
      json:
        name: json-routing-key
